export const TODOS_LIVROS = 'TODOS_LIVROS';
export const TODOS_LIVROS_SUCESSO = 'TODOS_LIVROS_SUCESSO';

export const LIVRO_POR_ID = 'LIVRO_POR_ID';
export const LIVRO_POR_ID_SUCESSO = 'LIVRO_POR_ID_SUCESSO';

export const ADICIONAR_LIVRO = 'ADICIONAR_LIVRO';
export const ADICIONAR_LIVRO_SUCESSO = 'ADICIONAR_LIVRO_SUCESSO';

export const ATUALIZAR_LIVRO = 'ATUALIZAR_LIVRO';
export const ATUALIZAR_LIVRO_SUCESSO = 'ATUALIZAR_LIVRO_SUCESSO';

export const REMOVER_LIVRO = 'REMOVER_LIVRO';
export const REMOVER_LIVRO_SUCESSO = 'REMOVER_LIVRO_SUCESSO';

export const TODOS_AUTORES = 'TODOS_AUTORES';
export const TODOS_AUTORES_SUCESSO = 'TODOS_AUTORES_SUCESSO';

export const TODAS_EDITORAS = 'TODAS_EDITORAS';
export const TODAS_EDITORAS_SUCESSO = 'TODAS_EDITORAS_SUCESSO';

