export const TODOS_LIVROS = 'TODOS_LIVROS';
export const TODOS_LIVROS_SUCESSO = 'TODOS_LIVROS_SUCESSO';

export const LIVRO_POR_ID = 'LIVRO_POR_ID';
export const LIVRO_POR_ID_SUCESSO = 'LIVRO_POR_ID_SUCESSO';

export const ADICIONAR_LIVRO = 'ADICIONAR_LIVRO';
export const ADICIONAR_LIVRO_SUCESSO = 'ADICIONAR_LIVRO_SUCESSO';
